/*==============================================================================

  Program: 3D Slicer

  Copyright (c) Kitware Inc.

  See COPYRIGHT.txt
  or http://www.slicer.org/copyright/copyright.txt for details.

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

  This file was originally developed by Jean-Christophe Fillion-Robin, Kitware Inc.
  and was partially funded by NIH grant 3P41RR013218-12S1

==============================================================================*/

// Qt includes
#include <QWeakPointer>
#include <QOpcUaClient>

// SiemensPlcOpcUa Widgets includes
#include "qSlicerSiemensPlcOpcUaWidget.h"
#include "ui_qSlicerSiemensPlcOpcUaWidget.h"

#include <vtkMRMLSiemensPlcOpcUaNode.h>

namespace {

const QString PARENT_NODE_DISPLAYED_NAME = "ServerInterfaces";

const QString RTK_PLC_NODE_NAME = PARENT_NODE_DISPLAYED_NAME + ".RTK_PLC";
const QString ASU_NODE_NAME = RTK_PLC_NODE_NAME + ".ASU";
const QString ASU_ERROR_MESSAGES_NODE_NAME = ASU_NODE_NAME + ".ErrorMes";
const QString ASU_SERVICE_MESSAGES_NODE_NAME = ASU_NODE_NAME + ".ServMes";
const QString ASU_MESSAGES_NODE_NAME = ASU_NODE_NAME + ".Messages";
const QString ASU_MODE_NODE_NAME = ASU_NODE_NAME + ".Mode";
const QString ASU_STATUS_RTK_NODE_NAME = ASU_NODE_NAME + ".Status_RTK";
const QString ASU_STATUS_R1_TABLE_NODE_NAME = ASU_NODE_NAME + ".Status_R1_deka";
const QString ASU_STATUS_R2_CARM_NODE_NAME = ASU_NODE_NAME + ".Status_R2_C_Duga";
const QString ASU_COORDS_NODE_NAME = ASU_NODE_NAME + ".CoordFromASU";
const QString ASU_COORDS_X_NODE_NAME = ASU_COORDS_NODE_NAME + ".X";
const QString ASU_COORDS_Y_NODE_NAME = ASU_COORDS_NODE_NAME + ".Y";
const QString ASU_COORDS_Z_NODE_NAME = ASU_COORDS_NODE_NAME + ".Z";
const QString ASU_COORDS_XRAY_Z_NODE_NAME = ASU_COORDS_NODE_NAME + ".XRAY_Z_correction";
const QString ASU_COORDS_R1_A_NODE_NAME = ASU_COORDS_NODE_NAME + ".AngleA_R1";
const QString ASU_COORDS_R1_B_NODE_NAME = ASU_COORDS_NODE_NAME + ".AngleB_R1";
const QString ASU_COORDS_R1_C_NODE_NAME = ASU_COORDS_NODE_NAME + ".AngleC_R1";

const QString IS_PRESSED = ".isPressed";
const QString IS_ENABLED = ".isEnable";

const QString BUTTONS_NODE_NAME = ASU_NODE_NAME + ".Buttons";
const QString BUTTONS_AM_NODE_NAME = BUTTONS_NODE_NAME + ".AM_MM";

const QString BUTTONS_AM_R1_LOADTOISO_NODE_NAME = BUTTONS_AM_NODE_NAME + ".R1_LoadToIso";
const QString BUTTONS_AM_R1_LOADTOISO_PRESSED_NODE_NAME = BUTTONS_AM_R1_LOADTOISO_NODE_NAME + IS_PRESSED;
const QString BUTTONS_AM_R1_LOADTOISO_ENABLED_NODE_NAME = BUTTONS_AM_R1_LOADTOISO_NODE_NAME + IS_ENABLED;

const QString BUTTONS_AM_R1_NEWCOORDS_NODE_NAME = BUTTONS_AM_NODE_NAME + ".R1_ToNewCoords";
const QString BUTTONS_AM_R1_NEWCOORDS_PRESSED_NODE_NAME = BUTTONS_AM_R1_NEWCOORDS_NODE_NAME + IS_PRESSED;
const QString BUTTONS_AM_R1_NEWCOORDS_ENABLED_NODE_NAME = BUTTONS_AM_R1_NEWCOORDS_NODE_NAME + IS_ENABLED;

const QString BUTTONS_AM_R1_TOLOAD_NODE_NAME = BUTTONS_AM_NODE_NAME + ".R1_ToLoad";
const QString BUTTONS_AM_R1_TOLOAD_PRESSED_NODE_NAME = BUTTONS_AM_R1_TOLOAD_NODE_NAME + IS_PRESSED;
const QString BUTTONS_AM_R1_TOLOAD_ENABLED_NODE_NAME = BUTTONS_AM_R1_TOLOAD_NODE_NAME + IS_ENABLED;

const QString BUTTONS_AM_R2_TOPLANE1_NODE_NAME = BUTTONS_AM_NODE_NAME + ".R2_ToPL1";
const QString BUTTONS_AM_R2_TOPLANE1_PRESSED_NODE_NAME = BUTTONS_AM_R2_TOPLANE1_NODE_NAME + IS_PRESSED;
const QString BUTTONS_AM_R2_TOPLANE1_ENABLED_NODE_NAME = BUTTONS_AM_R2_TOPLANE1_NODE_NAME + IS_ENABLED;

const QString BUTTONS_AM_R2_TOPLANE2_NODE_NAME = BUTTONS_AM_NODE_NAME + ".R2_ToPL2";
const QString BUTTONS_AM_R2_TOPLANE2_PRESSED_NODE_NAME = BUTTONS_AM_R2_TOPLANE2_NODE_NAME + IS_PRESSED;
const QString BUTTONS_AM_R2_TOPLANE2_ENABLED_NODE_NAME = BUTTONS_AM_R2_TOPLANE2_NODE_NAME + IS_ENABLED;

const QString BUTTONS_AM_R2_TOHOME_NODE_NAME = BUTTONS_AM_NODE_NAME + ".R2_ToHome";
const QString BUTTONS_AM_R2_TOHOME_PRESSED_NODE_NAME = BUTTONS_AM_R2_TOHOME_NODE_NAME + IS_PRESSED;
const QString BUTTONS_AM_R2_TOHOME_ENABLED_NODE_NAME = BUTTONS_AM_R2_TOHOME_NODE_NAME + IS_ENABLED;

const QString BUTTONS_AM_R1R2_EMEVAC_NODE_NAME = BUTTONS_AM_NODE_NAME + ".R1R2_EmEvac";
const QString BUTTONS_AM_R1R2_EMEVAC_PRESSED_NODE_NAME = BUTTONS_AM_R1R2_EMEVAC_NODE_NAME + IS_PRESSED;
const QString BUTTONS_AM_R1R2_EMEVAC_ENABLED_NODE_NAME = BUTTONS_AM_R1R2_EMEVAC_NODE_NAME + IS_ENABLED;

const QString BUTTONS_AM_APPLYTABLEPOSITION_NODE_NAME = BUTTONS_AM_NODE_NAME + ".ApplyDekaPosition";
const QString BUTTONS_AM_APPLYTABLEPOSITION_NODE_NAME_PRESSED_NODE_NAME = BUTTONS_AM_APPLYTABLEPOSITION_NODE_NAME + IS_PRESSED;
const QString BUTTONS_AM_APPLYTABLEPOSITION_NODE_NAME_ENABLED_NODE_NAME = BUTTONS_AM_APPLYTABLEPOSITION_NODE_NAME + IS_ENABLED;

const QString BUTTONS_SM_NODE_NAME = BUTTONS_NODE_NAME + ".SM";

const QString BUTTONS_SM_R1_BREAKTEST_NODE_NAME = BUTTONS_AM_NODE_NAME + ".BrakeTestR1";
const QString BUTTONS_SM_R1_BREAKTEST_PRESSED_NODE_NAME = BUTTONS_SM_R1_BREAKTEST_NODE_NAME + IS_PRESSED;
const QString BUTTONS_SM_R1_BREAKTEST_ENABLED_NODE_NAME = BUTTONS_SM_R1_BREAKTEST_NODE_NAME + IS_ENABLED;

const QString BUTTONS_SM_R1_MASREFTEST_NODE_NAME = BUTTONS_AM_NODE_NAME + ".MasterRefTestR1";
const QString BUTTONS_SM_R1_MASREFTEST_PRESSED_NODE_NAME = BUTTONS_SM_R1_MASREFTEST_NODE_NAME + IS_PRESSED;
const QString BUTTONS_SM_R1_MASREFTEST_ENABLED_NODE_NAME = BUTTONS_SM_R1_MASREFTEST_NODE_NAME + IS_ENABLED;

const QString BUTTONS_SM_R1_LOAD_NODE_NAME = BUTTONS_AM_NODE_NAME + ".LoadR1";
const QString BUTTONS_SM_R1_LOAD_PRESSED_NODE_NAME = BUTTONS_SM_R1_LOAD_NODE_NAME + IS_PRESSED;
const QString BUTTONS_SM_R1_LOAD_ENABLED_NODE_NAME = BUTTONS_SM_R1_LOAD_NODE_NAME + IS_ENABLED;

const QString BUTTONS_SM_R1_SERVICEPOS1_NODE_NAME = BUTTONS_AM_NODE_NAME + ".ServicePos1_R1";
const QString BUTTONS_SM_R1_SERVICEPOS1_PRESSED_NODE_NAME = BUTTONS_SM_R1_SERVICEPOS1_NODE_NAME + IS_PRESSED;
const QString BUTTONS_SM_R1_SERVICEPOS1_ENABLED_NODE_NAME = BUTTONS_SM_R1_SERVICEPOS1_NODE_NAME + IS_ENABLED;

const QString BUTTONS_SM_R1_SERVICEPOS2_NODE_NAME = BUTTONS_AM_NODE_NAME + ".ServicePos2_R1";
const QString BUTTONS_SM_R1_SERVICEPOS2_PRESSED_NODE_NAME = BUTTONS_SM_R1_SERVICEPOS2_NODE_NAME + IS_PRESSED;
const QString BUTTONS_SM_R1_SERVICEPOS2_ENABLED_NODE_NAME = BUTTONS_SM_R1_SERVICEPOS2_NODE_NAME + IS_ENABLED;

const QString BUTTONS_SM_R1_SERVICEPOS3_NODE_NAME = BUTTONS_AM_NODE_NAME + ".ServicePos3_R1";
const QString BUTTONS_SM_R1_SERVICEPOS3_PRESSED_NODE_NAME = BUTTONS_SM_R1_SERVICEPOS3_NODE_NAME + IS_PRESSED;
const QString BUTTONS_SM_R1_SERVICEPOS3_ENABLED_NODE_NAME = BUTTONS_SM_R1_SERVICEPOS3_NODE_NAME + IS_ENABLED;

const QString BUTTONS_SM_R2_BREAKTEST_NODE_NAME = BUTTONS_AM_NODE_NAME + ".BrakeTestR2";
const QString BUTTONS_SM_R2_BREAKTEST_PRESSED_NODE_NAME = BUTTONS_SM_R2_BREAKTEST_NODE_NAME + IS_PRESSED;
const QString BUTTONS_SM_R2_BREAKTEST_ENABLED_NODE_NAME = BUTTONS_SM_R2_BREAKTEST_NODE_NAME + IS_ENABLED;

const QString BUTTONS_SM_R2_MASREFTEST_NODE_NAME = BUTTONS_AM_NODE_NAME + ".MasterRefTestR2";
const QString BUTTONS_SM_R2_MASREFTEST_PRESSED_NODE_NAME = BUTTONS_SM_R2_MASREFTEST_NODE_NAME + IS_PRESSED;
const QString BUTTONS_SM_R2_MASREFTEST_ENABLED_NODE_NAME = BUTTONS_SM_R2_MASREFTEST_NODE_NAME + IS_ENABLED;

const QString BUTTONS_SM_R2_HOME_NODE_NAME = BUTTONS_AM_NODE_NAME + ".HomeR2";
const QString BUTTONS_SM_R2_HOME_PRESSED_NODE_NAME = BUTTONS_SM_R2_HOME_NODE_NAME + IS_PRESSED;
const QString BUTTONS_SM_R2_HOME_ENABLED_NODE_NAME = BUTTONS_SM_R2_HOME_NODE_NAME + IS_ENABLED;

const QString BUTTONS_SM_R2_SERVICEPOS1_NODE_NAME = BUTTONS_AM_NODE_NAME + ".ServicePos1_R2";
const QString BUTTONS_SM_R2_SERVICEPOS1_PRESSED_NODE_NAME = BUTTONS_SM_R2_SERVICEPOS1_NODE_NAME + IS_PRESSED;
const QString BUTTONS_SM_R2_SERVICEPOS1_ENABLED_NODE_NAME = BUTTONS_SM_R2_SERVICEPOS1_NODE_NAME + IS_ENABLED;

const QString BUTTONS_SM_R2_SERVICEPOS2_NODE_NAME = BUTTONS_AM_NODE_NAME + ".ServicePos2_R2";
const QString BUTTONS_SM_R2_SERVICEPOS2_PRESSED_NODE_NAME = BUTTONS_SM_R2_SERVICEPOS2_NODE_NAME + IS_PRESSED;
const QString BUTTONS_SM_R2_SERVICEPOS2_ENABLED_NODE_NAME = BUTTONS_SM_R2_SERVICEPOS2_NODE_NAME + IS_ENABLED;

const QString BUTTONS_SM_R2_SERVICEPOS3_NODE_NAME = BUTTONS_AM_NODE_NAME + ".ServicePos3_R2";
const QString BUTTONS_SM_R2_SERVICEPOS3_PRESSED_NODE_NAME = BUTTONS_SM_R2_SERVICEPOS3_NODE_NAME + IS_PRESSED;
const QString BUTTONS_SM_R2_SERVICEPOS3_ENABLED_NODE_NAME = BUTTONS_SM_R2_SERVICEPOS3_NODE_NAME + IS_ENABLED;

//  const QString SCADA_ERRORMESSAGES_NODE_ID = "ns=3;s=ServerInterfaces.RTK_PLC.ASU.ErrorMes";
//  const QString SCADA_SERVICEMESSAGES_NODE_ID = "ns=3;s=ServerInterfaces.RTK_PLC.ASU.ServMes";
//  const QString SCADA_MESSAGES_NODE_ID = "ns=3;s=ServerInterfaces.RTK_PLC.ASU.Messages";
/*

  const QString SCADA_TOASU_ERROR_MES_NODE_ID = SCADA_TOASU_NODE_ID + ".ErrorMes";
  const QString SCADA_TOASU_SERV_MES_NODE_ID = SCADA_TOASU_NODE_ID + ".ServMes";
  const QString SCADA_TOASU_MISC_MES_NODE_ID = SCADA_TOASU_NODE_ID + ".Messages";
  const QString SCADA_TOASU_MODE_NODE_ID = SCADA_TOASU_NODE_ID + ".Mode";
  const QString SCADA_TOASU_STATUS_RTK_NODE_ID = SCADA_TOASU_NODE_ID + ".Status_RTK";
  const QString SCADA_TOASU_STATUS_R1_DEKA_NODE_ID = SCADA_TOASU_NODE_ID + ".Status_R1_deka";
  const QString SCADA_TOASU_STATUS_R2_C_DUGA_NODE_ID = SCADA_TOASU_NODE_ID + ".Status_R2_C_Duga";
  const QString SCADA_TOASU_COORDFROMASU_NODE_ID = SCADA_TOASU_NODE_ID + ".CoordFromASU";
  const QString SCADA_TOASU_COORDFROMASU_X_NODE_ID = SCADA_TOASU_COORDFROMASU_NODE_ID + ".X";
  const QString SCADA_TOASU_COORDFROMASU_Y_NODE_ID = SCADA_TOASU_COORDFROMASU_NODE_ID + ".Y";
  const QString SCADA_TOASU_COORDFROMASU_Z_NODE_ID = SCADA_TOASU_COORDFROMASU_NODE_ID + ".Z";
  const QString SCADA_TOASU_COORDFROMASU_XRAY_Z_CORRECTION_NODE_ID = SCADA_TOASU_COORDFROMASU_NODE_ID + ".XRAY_Z_correction";
  const QString SCADA_TOASU_COORDFROMASU_ANGLEA_R1_NODE_ID = SCADA_TOASU_COORDFROMASU_NODE_ID + ".AngleA_R1";
  const QString SCADA_TOASU_COORDFROMASU_ANGLEB_R1_NODE_ID = SCADA_TOASU_COORDFROMASU_NODE_ID + ".AngleB_R1";
  const QString SCADA_TOASU_COORDFROMASU_ANGLEC_R1_NODE_ID = SCADA_TOASU_COORDFROMASU_NODE_ID + ".AngleC_R1";
  const QString SCADA_TOASU_BUTTONS_NODE_ID = SCADA_TOASU_NODE_ID + ".Buttons";
  const QString SCADA_TOASU_BUTTONS_AM_NODE_ID = SCADA_TOASU_BUTTONS_NODE_ID + ".AM_MM";
*/
//  const QString IS_PRESSED = ".isPressed";
/*
  const QString IS_ENABLE = ".isEnable";
  const QString SCADA_TOASU_BUTTONS_AM_R1_LOADTOISO_NODE_ID = SCADA_TOASU_BUTTONS_AM_NODE_ID + ".R1_LoadToIso";
  const QString SCADA_TOASU_BUTTONS_AM_R1_LOADTOISO_ISPRESSED_NODE_ID = SCADA_TOASU_BUTTONS_AM_R1_LOADTOISO_NODE_ID + IS_PRESSED;
  const QString SCADA_TOASU_BUTTONS_AM_R1_LOADTOISO_ISENABLE_NODE_ID = SCADA_TOASU_BUTTONS_AM_R1_LOADTOISO_NODE_ID + IS_ENABLE;

  const QString SCADA_TOASU_BUTTONS_AM_R1_TONEWCOORDS_NODE_ID = SCADA_TOASU_BUTTONS_AM_NODE_ID + ".R1_ToNewCoords";
  const QString SCADA_TOASU_BUTTONS_AM_R1_TONEWCOORDS_ISPRESSED_NODE_ID = SCADA_TOASU_BUTTONS_AM_R1_TONEWCOORDS_NODE_ID + IS_PRESSED;
  const QString SCADA_TOASU_BUTTONS_AM_R1_TONEWCOORDS_ISENABLE_NODE_ID = SCADA_TOASU_BUTTONS_AM_R1_TONEWCOORDS_NODE_ID + IS_ENABLE;

  const QString SCADA_TOASU_BUTTONS_AM_R1_TOLOAD_NODE_ID = SCADA_TOASU_BUTTONS_AM_NODE_ID + ".R1_ToLoad";
  const QString SCADA_TOASU_BUTTONS_AM_R1_TOLOAD_ISPRESSED_NODE_ID = SCADA_TOASU_BUTTONS_AM_R1_TOLOAD_NODE_ID + IS_PRESSED;
  const QString SCADA_TOASU_BUTTONS_AM_R1_TOLOAD_ISENABLE_NODE_ID = SCADA_TOASU_BUTTONS_AM_R1_TOLOAD_NODE_ID + IS_ENABLE;

  const QString SCADA_TOASU_BUTTONS_AM_R2_TOPL1_NODE_ID = SCADA_TOASU_BUTTONS_AM_NODE_ID + ".R2_ToPL1";
  const QString SCADA_TOASU_BUTTONS_AM_R2_TOPL1_ISPRESSED_NODE_ID = SCADA_TOASU_BUTTONS_AM_R2_TOPL1_NODE_ID + IS_PRESSED;
  const QString SCADA_TOASU_BUTTONS_AM_R2_TOPL1_ISENABLE_NODE_ID = SCADA_TOASU_BUTTONS_AM_R2_TOPL1_NODE_ID + IS_ENABLE;

  const QString SCADA_TOASU_BUTTONS_AM_R2_TOPL2_NODE_ID = SCADA_TOASU_BUTTONS_AM_NODE_ID + ".R2_ToPL2";
  const QString SCADA_TOASU_BUTTONS_AM_R2_TOPL2_ISPRESSED_NODE_ID = SCADA_TOASU_BUTTONS_AM_R2_TOPL2_NODE_ID + IS_PRESSED;
  const QString SCADA_TOASU_BUTTONS_AM_R2_TOPL2_ISENABLE_NODE_ID = SCADA_TOASU_BUTTONS_AM_R2_TOPL2_NODE_ID + IS_ENABLE;

  const QString SCADA_TOASU_BUTTONS_AM_R2_TOHOME_NODE_ID = SCADA_TOASU_BUTTONS_AM_NODE_ID + ".R2_ToHome";
  const QString SCADA_TOASU_BUTTONS_AM_R2_TOHOME_ISPRESSED_NODE_ID = SCADA_TOASU_BUTTONS_AM_R2_TOHOME_NODE_ID + IS_PRESSED;
  const QString SCADA_TOASU_BUTTONS_AM_R2_TOHOME_ISENABLE_NODE_ID = SCADA_TOASU_BUTTONS_AM_R2_TOHOME_NODE_ID + IS_ENABLE;

  const QString SCADA_TOASU_BUTTONS_AM_R1R2_EMEVAC_NODE_ID = SCADA_TOASU_BUTTONS_AM_NODE_ID + ".R1R2_EmEvac";
  const QString SCADA_TOASU_BUTTONS_AM_R1R2_EMEVAC_ISPRESSED_NODE_ID = SCADA_TOASU_BUTTONS_AM_R1R2_EMEVAC_NODE_ID + IS_PRESSED;
  const QString SCADA_TOASU_BUTTONS_AM_R1R2_EMEVAC_ISENABLE_NODE_ID = SCADA_TOASU_BUTTONS_AM_R1R2_EMEVAC_NODE_ID + IS_ENABLE;

  const QString SCADA_TOASU_BUTTONS_SM_NODE_ID = SCADA_TOASU_BUTTONS_NODE_ID + ".SM";
  const QString SCADA_TOASU_BUTTONS_SM_BRAKETESTR1_NODE_ID = SCADA_TOASU_BUTTONS_SM_NODE_ID + ".BreakTestR1";
  const QString SCADA_TOASU_BUTTONS_SM_BRAKETESTR1_ISPRESSED_NODE_ID = SCADA_TOASU_BUTTONS_SM_BRAKETESTR1_NODE_ID + IS_PRESSED;
  const QString SCADA_TOASU_BUTTONS_SM_BRAKETESTR1_ISENABLE_NODE_ID = SCADA_TOASU_BUTTONS_SM_BRAKETESTR1_NODE_ID + IS_ENABLE;

  const QString SCADA_TOASU_BUTTONS_SM_MASREFTESTR1_NODE_ID = SCADA_TOASU_BUTTONS_SM_NODE_ID + ".MasRefTestR1";
  const QString SCADA_TOASU_BUTTONS_SM_MASREFTESTR1_ISPRESSED_NODE_ID = SCADA_TOASU_BUTTONS_SM_MASREFTESTR1_NODE_ID + IS_PRESSED;
  const QString SCADA_TOASU_BUTTONS_SM_MASREFTESTR1_ISENABLE_NODE_ID = SCADA_TOASU_BUTTONS_SM_MASREFTESTR1_NODE_ID + IS_ENABLE;

  const QString SCADA_TOASU_BUTTONS_SM_LOADR1_NODE_ID = SCADA_TOASU_BUTTONS_SM_NODE_ID + ".LoadR1";
  const QString SCADA_TOASU_BUTTONS_SM_LOADR1_ISPRESSED_NODE_ID = SCADA_TOASU_BUTTONS_SM_LOADR1_NODE_ID + IS_PRESSED;
  const QString SCADA_TOASU_BUTTONS_SM_LOADR1_ISENABLE_NODE_ID = SCADA_TOASU_BUTTONS_SM_LOADR1_NODE_ID + IS_ENABLE;

  const QString SCADA_TOASU_BUTTONS_SM_SERVICEPOS1R1_NODE_ID = SCADA_TOASU_BUTTONS_SM_NODE_ID + ".ServicePos1_R1";
  const QString SCADA_TOASU_BUTTONS_SM_SERVICEPOS1R1_ISPRESSED_NODE_ID = SCADA_TOASU_BUTTONS_SM_SERVICEPOS1R1_NODE_ID + IS_PRESSED;
  const QString SCADA_TOASU_BUTTONS_SM_SERVICEPOS1R1_ISENABLE_NODE_ID = SCADA_TOASU_BUTTONS_SM_SERVICEPOS1R1_NODE_ID + IS_ENABLE;

  const QString SCADA_TOASU_BUTTONS_SM_SERVICEPOS2R1_NODE_ID = SCADA_TOASU_BUTTONS_SM_NODE_ID + ".ServicePos1_R1";
  const QString SCADA_TOASU_BUTTONS_SM_SERVICEPOS2R1_ISPRESSED_NODE_ID = SCADA_TOASU_BUTTONS_SM_SERVICEPOS2R1_NODE_ID + IS_PRESSED;
  const QString SCADA_TOASU_BUTTONS_SM_SERVICEPOS2R1_ISENABLE_NODE_ID = SCADA_TOASU_BUTTONS_SM_SERVICEPOS2R1_NODE_ID + IS_ENABLE;

  const QString SCADA_TOASU_BUTTONS_SM_SERVICEPOS3R1_NODE_ID = SCADA_TOASU_BUTTONS_SM_NODE_ID + ".ServicePos1_R1";
  const QString SCADA_TOASU_BUTTONS_SM_SERVICEPOS3R1_ISPRESSED_NODE_ID = SCADA_TOASU_BUTTONS_SM_SERVICEPOS3R1_NODE_ID + IS_PRESSED;
  const QString SCADA_TOASU_BUTTONS_SM_SERVICEPOS3R1_ISENABLE_NODE_ID = SCADA_TOASU_BUTTONS_SM_SERVICEPOS3R1_NODE_ID + IS_ENABLE;

  const QString SCADA_TOASU_BUTTONS_SM_BRAKETESTR2_NODE_ID = SCADA_TOASU_BUTTONS_SM_NODE_ID + ".BreakTestR2";
  const QString SCADA_TOASU_BUTTONS_SM_BRAKETESTR2_ISPRESSED_NODE_ID = SCADA_TOASU_BUTTONS_SM_BRAKETESTR2_NODE_ID + IS_PRESSED;
  const QString SCADA_TOASU_BUTTONS_SM_BRAKETESTR2_ISENABLE_NODE_ID = SCADA_TOASU_BUTTONS_SM_BRAKETESTR2_NODE_ID + IS_ENABLE;

  const QString SCADA_TOASU_BUTTONS_SM_MASREFTESTR2_NODE_ID = SCADA_TOASU_BUTTONS_SM_NODE_ID + ".MasRefTestR2";
  const QString SCADA_TOASU_BUTTONS_SM_MASREFTESTR2_ISPRESSED_NODE_ID = SCADA_TOASU_BUTTONS_SM_MASREFTESTR2_NODE_ID + IS_PRESSED;
  const QString SCADA_TOASU_BUTTONS_SM_MASREFTESTR2_ISENABLE_NODE_ID = SCADA_TOASU_BUTTONS_SM_MASREFTESTR2_NODE_ID + IS_ENABLE;

  const QString SCADA_TOASU_BUTTONS_SM_HOMER2_NODE_ID = SCADA_TOASU_BUTTONS_SM_NODE_ID + ".HomeR2";
  const QString SCADA_TOASU_BUTTONS_SM_HOMER2_ISPRESSED_NODE_ID = SCADA_TOASU_BUTTONS_SM_HOMER2_NODE_ID + IS_PRESSED;
  const QString SCADA_TOASU_BUTTONS_SM_HOMER2_ISENABLE_NODE_ID = SCADA_TOASU_BUTTONS_SM_HOMER2_NODE_ID + IS_ENABLE;

  const QString SCADA_TOASU_BUTTONS_SM_SERVICEPOS1R2_NODE_ID = SCADA_TOASU_BUTTONS_SM_NODE_ID + ".ServicePos1_R2";
  const QString SCADA_TOASU_BUTTONS_SM_SERVICEPOS1R2_ISPRESSED_NODE_ID = SCADA_TOASU_BUTTONS_SM_SERVICEPOS1R2_NODE_ID + IS_PRESSED;
  const QString SCADA_TOASU_BUTTONS_SM_SERVICEPOS1R2_ISENABLE_NODE_ID = SCADA_TOASU_BUTTONS_SM_SERVICEPOS1R2_NODE_ID + IS_ENABLE;

  const QString SCADA_TOASU_BUTTONS_SM_SERVICEPOS2R2_NODE_ID = SCADA_TOASU_BUTTONS_SM_NODE_ID + ".ServicePos2_R2";
  const QString SCADA_TOASU_BUTTONS_SM_SERVICEPOS2R2_ISPRESSED_NODE_ID = SCADA_TOASU_BUTTONS_SM_SERVICEPOS2R2_NODE_ID + IS_PRESSED;
  const QString SCADA_TOASU_BUTTONS_SM_SERVICEPOS2R2_ISENABLE_NODE_ID = SCADA_TOASU_BUTTONS_SM_SERVICEPOS2R2_NODE_ID + IS_ENABLE;

  const QString SCADA_TOASU_BUTTONS_SM_SERVICEPOS3R2_NODE_ID = SCADA_TOASU_BUTTONS_SM_NODE_ID + ".ServicePos3_R2";
  const QString SCADA_TOASU_BUTTONS_SM_SERVICEPOS3R2_ISPRESSED_NODE_ID = SCADA_TOASU_BUTTONS_SM_SERVICEPOS3R2_NODE_ID + IS_PRESSED;
  const QString SCADA_TOASU_BUTTONS_SM_SERVICEPOS3R2_ISENABLE_NODE_ID = SCADA_TOASU_BUTTONS_SM_SERVICEPOS3R2_NODE_ID + IS_ENABLE;

  const QString SCADA_TOASU_BUTTONS_SM_RESTARTSM_NODE_ID = SCADA_TOASU_BUTTONS_SM_NODE_ID + ".RestartSM";
  const QString SCADA_TOASU_BUTTONS_SM_RESTARTSM_ISPRESSED_NODE_ID = SCADA_TOASU_BUTTONS_SM_RESTARTSM_NODE_ID + IS_PRESSED;
  const QString SCADA_TOASU_BUTTONS_SM_RESTARTSM_ISENABLE_NODE_ID = SCADA_TOASU_BUTTONS_SM_RESTARTSM_NODE_ID + IS_ENABLE;

  const QString SCADA_TOASU_BUTTONS_KCM_NODE_ID = SCADA_TOASU_BUTTONS_NODE_ID + ".KCM";
  const QString SCADA_TOASU_BUTTONS_KCM_ALLOWT1_NODE_ID = SCADA_TOASU_BUTTONS_KCM_NODE_ID + ".AllowT1";
  const QString SCADA_TOASU_BUTTONS_KCM_ALLOWT1_ISPRESSED_NODE_ID = SCADA_TOASU_BUTTONS_KCM_ALLOWT1_NODE_ID + IS_PRESSED;
  const QString SCADA_TOASU_BUTTONS_KCM_ALLOWT1_ISENABLE_NODE_ID = SCADA_TOASU_BUTTONS_KCM_ALLOWT1_NODE_ID + IS_ENABLE;

  const QString SCADA_TOASU_BUTTONS_KCM_ALLOWXRAY_NODE_ID = SCADA_TOASU_BUTTONS_KCM_NODE_ID + ".AllowXRay";
  const QString SCADA_TOASU_BUTTONS_KCM_ALLOWXRAY_ISPRESSED_NODE_ID = SCADA_TOASU_BUTTONS_KCM_ALLOWXRAY_NODE_ID + IS_PRESSED;
  const QString SCADA_TOASU_BUTTONS_KCM_ALLOWXRAY_ISENABLE_NODE_ID = SCADA_TOASU_BUTTONS_KCM_ALLOWXRAY_NODE_ID + IS_ENABLE;

  const QString SCADA_TOASU_BUTTONS_KCM_ALLOWBEAM_NODE_ID = SCADA_TOASU_BUTTONS_KCM_NODE_ID + ".AllowBeam";
  const QString SCADA_TOASU_BUTTONS_KCM_ALLOWBEAM_ISPRESSED_NODE_ID = SCADA_TOASU_BUTTONS_KCM_ALLOWBEAM_NODE_ID + IS_PRESSED;
  const QString SCADA_TOASU_BUTTONS_KCM_ALLOWBEAM_ISENABLE_NODE_ID = SCADA_TOASU_BUTTONS_KCM_ALLOWBEAM_NODE_ID + IS_ENABLE;

  const QString SCADA_TOASU_BUTTONS_RESETERRORS_NODE_ID = SCADA_TOASU_BUTTONS_NODE_ID + ".ResetErrors";
  const QString SCADA_TOASU_BUTTONS_RESETERRORS_ISPRESSED_NODE_ID = SCADA_TOASU_BUTTONS_RESETERRORS_NODE_ID + IS_PRESSED;
  const QString SCADA_TOASU_BUTTONS_RESETERRORS_ISENABLE_NODE_ID = SCADA_TOASU_BUTTONS_RESETERRORS_NODE_ID + IS_ENABLE;

  const QString SCADA_TOASU_BUTTONS_MAKEXRAY_NODE_ID = SCADA_TOASU_BUTTONS_NODE_ID + ".MakeXRay";
  const QString SCADA_TOASU_BUTTONS_MAKEXRAY_ISPRESSED_NODE_ID = SCADA_TOASU_BUTTONS_MAKEXRAY_NODE_ID + IS_PRESSED;
  const QString SCADA_TOASU_BUTTONS_MAKEXRAY_ISENABLE_NODE_ID = SCADA_TOASU_BUTTONS_MAKEXRAY_NODE_ID + IS_ENABLE;

  const QString SCADA_TOASU_ROBOTSREADYFORXRAY1_NODE_ID = SCADA_TOASU_NODE_ID + ".RobotsReadyForXray1";
  const QString SCADA_TOASU_ROBOTSREADYFORXRAY2_NODE_ID = SCADA_TOASU_NODE_ID + ".RobotsReadyForXray2";
  const QString SCADA_TOASU_ROBOTSREADYFORBEAM_NODE_ID = SCADA_TOASU_NODE_ID + ".RobotsReadyForBeam";
  const QString SCADA_TOASU_HUMANONDEKA_NODE_ID = SCADA_TOASU_NODE_ID + ".HUMAN_ON_DEKA";
  const QString SCADA_TOASU_LOCKSENSOR_NODE_ID = SCADA_TOASU_NODE_ID + ".LockSensor";
  const QString SCADA_TOASU_LOCKSENSOR2_NODE_ID = SCADA_TOASU_NODE_ID + ".LockSensor2";
  const QString SCADA_TOASU_DEKAPOSITION_NODE_ID = SCADA_TOASU_NODE_ID + ".DekaPosition";
  const QString SCADA_TOASU_EMEVACSIGNAL_NODE_ID = SCADA_TOASU_NODE_ID + ".EmEvacuationSignal";

  const QString SCADA_KUKA_X_COORDINATE_TO_TCS_R1_NODE_ID = SCADA_TOASU_NODE_ID + ".KUKA_X_coordinate_to_TCS_R1";
  const QString SCADA_KUKA_Y_COORDINATE_TO_TCS_R1_NODE_ID = SCADA_TOASU_NODE_ID + ".KUKA_Y_coordinate_to_TCS_R1";
  const QString SCADA_KUKA_Z_COORDINATE_TO_TCS_R1_NODE_ID = SCADA_TOASU_NODE_ID + ".KUKA_Z_coordinate_to_TCS_R1";

  const QString SCADA_AXIS_CORD_A1_R1_NODE_ID = SCADA_TOASU_NODE_ID + ".AXIS_cord_A1_R1";
  const QString SCADA_AXIS_CORD_A2_R1_NODE_ID = SCADA_TOASU_NODE_ID + ".AXIS_cord_A2_R1";
  const QString SCADA_AXIS_CORD_A3_R1_NODE_ID = SCADA_TOASU_NODE_ID + ".AXIS_cord_A3_R1";
  const QString SCADA_AXIS_CORD_A4_R1_NODE_ID = SCADA_TOASU_NODE_ID + ".AXIS_cord_A4_R1";
  const QString SCADA_AXIS_CORD_A5_R1_NODE_ID = SCADA_TOASU_NODE_ID + ".AXIS_cord_A5_R1";
  const QString SCADA_AXIS_CORD_A6_R1_NODE_ID = SCADA_TOASU_NODE_ID + ".AXIS_cord_A6_R1";

  const QString SCADA_AXIS_CORD_A1_R2_NODE_ID = SCADA_TOASU_NODE_ID + ".AXIS_cord_A1_R2";
  const QString SCADA_AXIS_CORD_A2_R2_NODE_ID = SCADA_TOASU_NODE_ID + ".AXIS_cord_A2_R2";
  const QString SCADA_AXIS_CORD_A3_R2_NODE_ID = SCADA_TOASU_NODE_ID + ".AXIS_cord_A3_R2";
  const QString SCADA_AXIS_CORD_A4_R2_NODE_ID = SCADA_TOASU_NODE_ID + ".AXIS_cord_A4_R2";
  const QString SCADA_AXIS_CORD_A5_R2_NODE_ID = SCADA_TOASU_NODE_ID + ".AXIS_cord_A5_R2";
  const QString SCADA_AXIS_CORD_A6_R2_NODE_ID = SCADA_TOASU_NODE_ID + ".AXIS_cord_A6_R2";
*/
}

//-----------------------------------------------------------------------------
class qSlicerSiemensPlcOpcUaWidgetPrivate : public Ui_qSlicerSiemensPlcOpcUaWidget
{
  Q_DECLARE_PUBLIC(qSlicerSiemensPlcOpcUaWidget)
protected:
  qSlicerSiemensPlcOpcUaWidget* const q_ptr;

public:
  qSlicerSiemensPlcOpcUaWidgetPrivate(qSlicerSiemensPlcOpcUaWidget& object);
  virtual void setupUi(qSlicerSiemensPlcOpcUaWidget*);
  bool ParseServerParentNode();

  QWeakPointer< QOpcUaClient > OpcUaClient;
  vtkWeakPointer< vtkMRMLSiemensPlcOpcUaNode > ParameterNode;

  // Messages nodes
  QScopedPointer<QOpcUaNode> ErrorMessagesNode;
  QScopedPointer<QOpcUaNode> ServiceMessagesNode;
  QScopedPointer<QOpcUaNode> MiscMessagesNode;

  // Parse parent node
  const QString SIEMENS_PLC_SERVER_INTERFACES_NODE_ID = "ns=3;s=ServerInterfacesns=3;s=ServerInterfaces";
  QScopedPointer<QOpcUaNode> ServerInterfacesNode;
  // Monitored node
  const QString SIEMENS_PLC_CURRENT_TIME_NODE_ID = "ns=0;i=2258";
  QScopedPointer<QOpcUaNode> CurrentTimeNode; // Siemens PLC monitored node to prevent session timeout ending

  QMap< QString, QString > NodeIdNameMap;
};

// --------------------------------------------------------------------------
qSlicerSiemensPlcOpcUaWidgetPrivate::qSlicerSiemensPlcOpcUaWidgetPrivate(qSlicerSiemensPlcOpcUaWidget& object)
  : q_ptr(&object)
{
}

// --------------------------------------------------------------------------
void qSlicerSiemensPlcOpcUaWidgetPrivate::setupUi(qSlicerSiemensPlcOpcUaWidget* widget)
{
  this->Ui_qSlicerSiemensPlcOpcUaWidget::setupUi(widget);
}

bool qSlicerSiemensPlcOpcUaWidgetPrivate::ParseServerParentNode()
{
  return true;
}

//-----------------------------------------------------------------------------
// qSlicerScadaOpcUaRobotsControlWidget methods

//-----------------------------------------------------------------------------
qSlicerSiemensPlcOpcUaWidget::qSlicerSiemensPlcOpcUaWidget(QWidget* parentWidget)
  : Superclass( parentWidget )
  , d_ptr( new qSlicerSiemensPlcOpcUaWidgetPrivate(*this) )
{
  Q_D(qSlicerSiemensPlcOpcUaWidget);
  d->setupUi(this);
}

//-----------------------------------------------------------------------------
qSlicerSiemensPlcOpcUaWidget::~qSlicerSiemensPlcOpcUaWidget()
{
}

void qSlicerSiemensPlcOpcUaWidget::setParameterNode(vtkMRMLNode* node)
{
  Q_D(qSlicerSiemensPlcOpcUaWidget);

  vtkMRMLSiemensPlcOpcUaNode* parameterNode = vtkMRMLSiemensPlcOpcUaNode::SafeDownCast(node);
  // Each time the node is modified, the UI widgets are updated
  qvtkReconnect(d->ParameterNode, parameterNode, vtkCommand::ModifiedEvent, 
    this, SLOT(updateWidgetFromMRML()));

  d->ParameterNode = parameterNode;

  this->updateWidgetFromMRML();
}

void qSlicerSiemensPlcOpcUaWidget::setSiemensPlcOpcUaClient(const QSharedPointer< QOpcUaClient >& sharedClient)
{
  Q_D(qSlicerSiemensPlcOpcUaWidget);

  d->OpcUaClient = sharedClient;
}

void qSlicerSiemensPlcOpcUaWidget::updateWidgetFromMRML()
{
  Q_D(qSlicerSiemensPlcOpcUaWidget);
  if (!d->ParameterNode)
  {
    return;
  }
  switch (d->ParameterNode->GetMode())
  {
  case vtkMRMLSiemensPlcOpcUaNode::AUTOMATIC_MANUAL:
    break;
  case vtkMRMLSiemensPlcOpcUaNode::SERVICE:
    break;
  case vtkMRMLSiemensPlcOpcUaNode::KUKA_CONTROLLERS:
    break;
  case vtkMRMLSiemensPlcOpcUaNode::UNKNOWN:
  default:
    break;
  }

  qDebug() << Q_FUNC_INFO << "Update SiemensPlcOpcUa buttons";
}

void qSlicerSiemensPlcOpcUaWidget::onOpcUaClientConnected()
{
  Q_D(qSlicerSiemensPlcOpcUaWidget);
  
  QSharedPointer< QOpcUaClient > sharedClient = d->OpcUaClient.toStrongRef();
  if (!sharedClient)
  {
    return;
  }
  d->ServerInterfacesNode.reset(sharedClient->node(d->SIEMENS_PLC_SERVER_INTERFACES_NODE_ID));

  d->CurrentTimeNode.reset(sharedClient->node(d->SIEMENS_PLC_CURRENT_TIME_NODE_ID));
  // Subscribe to data changes
  d->CurrentTimeNode->enableMonitoring(QOpcUa::NodeAttribute::Value, QOpcUaMonitoringParameters(1000));
}

void qSlicerSiemensPlcOpcUaWidget::onOpcUaClientDisconnected()
{
}
